name: fasting_mate_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2          # Untuk HTTP request ke API Laravel
  flutter_riverpod: ^2.3.6  # State management
  shared_preferences: ^2.2.0  # Menyimpan token login
  flutter_secure_storage: ^9.0.0 # Menyimpan token secara aman
  intl: ^0.18.0  # Format tanggal dan waktu
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
